# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    # The docs dependency group requires 3.12 or later.
    python: "3.14"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
  - method: uv
    command: sync
    groups:
    - docs
