# Copyright header configuration for ruff's CPY001 check.
#
# The header below is a regular expression, so its parentheses and periods
# are escaped, and the leading `\A` anchors the match to the start of the
# file.
#
# The end year here is the single source of truth: CPY001 holds every source
# file to it, and the check-copyright-year workflow holds it to the current
# year.

[lint.flake8-copyright]
# Empty files don't need a copyright header.
min-file-size = 1
notice-rgx = '''\A# \(C\) Copyright 2007-2026 Enthought, Inc\., Austin, TX
# All rights reserved\.
#
# This software is provided without warranty under the terms of the BSD
# license included in LICENSE\.txt and may be redistributed only under
# the conditions described in the aforementioned license\. The license
# is also available online at http://www\.enthought\.com/licenses/BSD\.txt
#
# Thanks for using Enthought open source!'''
