name: install-qt-support
description: 'Install supporting OS packages for Qt-using code'
runs:
  using: composite
  steps:
  - name: Install Linux packages for Qt
    if: runner.os == 'Linux'
    run: |
      sudo apt-get update
      sudo apt-get install libegl1
      sudo apt-get install libxkbcommon-x11-0
      sudo apt-get install libxcb-icccm4
      sudo apt-get install libxcb-image0
      sudo apt-get install libxcb-keysyms1
      sudo apt-get install libxcb-randr0
      sudo apt-get install libxcb-render-util0
      sudo apt-get install libxcb-shape0
      # Needed to work around https://bugreports.qt.io/browse/PYSIDE-1547
      sudo apt-get install libopengl0
    shell: bash
