name: Test the documentation build

on: [pull_request, workflow_dispatch]

env:
  UV_PYTHON: '3.14'

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up uv
      uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
      with:
        enable-cache: true
        cache-dependency-glob: 'docs/requirements.txt'
    - run: |
        uv venv
        uv pip install -r docs/requirements.txt .
    - run: |
        uv run --no-project python -m sphinx -b html -d docs/build/doctrees docs/source docs/build/html
    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: documentation
        path: |
          docs/build/
          !docs/build/doctrees/
