name: Test with EDM

on: [pull_request, workflow_dispatch]

env:
  INSTALL_EDM_VERSION: 4.1.5
  PYTHONUNBUFFERED: 1
  # EDM's installer doesn't support extras, hence the explicit configobj.
  EDM_PACKAGES: apptools configobj pyface pygments pytest traits traitsui

jobs:

  test-with-edm:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        runtime: ['3.11']
        toolkit: ['null', 'pyside6']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone the Envisage source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install packages for Qt support
        uses: ./.github/actions/install-qt-support
      - name: Cache EDM packages
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ matrix.runtime }}-${{ matrix.toolkit }}-${{ hashFiles('.github/workflows/test-with-edm.yml') }}
      - name: Set up EDM
        uses: enthought/setup-edm-action@e68a4e0282298d695020fb21b4d3e93c3ac3c11f # v4.2
        with:
          edm-version: ${{ env.INSTALL_EDM_VERSION }}
      - name: Create the EDM environment
        run: edm environments create envisage --force --version=${{ matrix.runtime }}
      - name: Install dependencies
        run: edm --config .github/edm.yaml install -y -e envisage ${{ env.EDM_PACKAGES }}
      - name: Install the GUI toolkit
        if: matrix.toolkit != 'null'
        run: edm --config .github/edm.yaml install -y -e envisage ${{ matrix.toolkit }}
      - name: Install the package under test
        run: edm run -e envisage -- python -m pip install . --no-dependencies
      # Run from outside the source tree, to exercise the installed package.
      - name: Run tests (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        working-directory: ${{ runner.temp }}
        run: xvfb-run -a edm run -e envisage -- python -m pytest -c ${{ github.workspace }}/pyproject.toml --pyargs envisage
      - name: Run tests (not Ubuntu)
        if: matrix.os != 'ubuntu-latest'
        working-directory: ${{ runner.temp }}
        run: edm run -e envisage -- python -m pytest -c ${{ github.workspace }}/pyproject.toml --pyargs envisage
