name: Run the test suite on wxPython

on:
  schedule:
    - cron:  '0 0 * * 5'

env:
  INSTALL_EDM_VERSION: 3.2.3

jobs:

  # Test against EDM packages
  test-with-edm:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        toolkit: ['wx']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Wx dependencies for Linux
        run: |
          sudo apt-get update
          sudo apt-get install libsdl-image1.2
          sudo apt-get install libsdl2-2.0-0
        shell: bash
      - name: Cache EDM packages
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-${{ matrix.toolkit }}-${{ hashFiles('etstool.py') }}
      - name: Setup EDM
        uses: enthought/setup-edm-action@v1
        with:
          edm-version: ${{ env.INSTALL_EDM_VERSION }}
      - name: Install click to the default EDM environment
        run: edm install -y wheel click coverage
      - name: Install test environment
        run: edm run -- python etstool.py install --toolkit=${{ matrix.toolkit }}
      - name: Run tests
        uses: GabrielBB/xvfb-action@v1
        with:
          run: edm run -- python etstool.py test --toolkit=${{ matrix.toolkit }}
