name: Test with PyPI

on: [pull_request, workflow_dispatch]

env:
  PYTHONUNBUFFERED: 1

jobs:

  # Test against PyPI packages, using pytest
  test-with-pypi:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: ['3.10', '3.11', '3.12', '3.13', '3.14', '3.15']

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone the Envisage source
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install packages for Qt support
        uses: ./.github/actions/install-qt-support
      - name: Set up uv
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: 'pyproject.toml'
      - name: List the packages under test
        run: uv tree --group test
      - name: Run tests (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: xvfb-run -a uv run --group test -- python -m pytest
      - name: Run tests (not Ubuntu)
        if: matrix.os != 'ubuntu-latest'
        run: uv run --group test -- python -m pytest
