name: Update gh-pages documentation

# To do:
# - [ ] Switch out the pull_request trigger and trigger on push to main
#       instead. (But keep the workflow dispatch trigger.)
# - [ ] Replace gh-pages-staging with gh-pages throughout.

on: [pull_request, workflow_dispatch]

jobs:
  update-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: 'docs/requirements.txt'
    - run: |
        python -m pip install -r docs/requirements.txt
        python -m pip install .
    - run: |
        python -m sphinx -b html -d docs/build/doctrees docs/source docs/build/html
    - name: Check out gh-pages-staging branch
      run: |
        git worktree add ../docs gh-pages-staging
    - name: Update the docs on the gh-pages-staging branch
      run: |
        python graft_docs.py
